/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#404943",
        "primary-fixed": "#b8efd2",
        "inverse-on-surface": "#f8f0e2",
        "primary": "#003623",
        "on-tertiary-fixed-variant": "#643f00",
        "on-tertiary-container": "#e1a758",
        "tertiary": "#432900",
        "secondary": "#5f5e5a",
        "surface-dim": "#e1d9cb",
        "inverse-surface": "#343027",
        "surface-container-low": "#fbf3e5",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e5e2dd",
        "on-error": "#ffffff",
        "primary-container": "#184d38",
        "on-secondary-fixed": "#1c1c19",
        "tertiary-fixed": "#ffddb5",
        "primary-fixed-dim": "#9cd2b6",
        "outline-variant": "#c0c9c2",
        "outline": "#717973",
        "tertiary-container": "#613d00",
        "on-primary": "#ffffff",
        "on-background": "#1e1b13",
        "on-primary-container": "#88bda2",
        "secondary-container": "#e2dfda",
        "on-primary-fixed": "#002114",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#2a1800",
        "surface-container-highest": "#e9e2d4",
        "surface-container": "#f5eddf",
        "inverse-primary": "#9cd2b6",
        "on-secondary-fixed-variant": "#474743",
        "error": "#ba1a1a",
        "on-secondary-container": "#63635f",
        "on-surface": "#1e1b13",
        "on-secondary": "#ffffff",
        "surface": "#fff8f0",
        "on-primary-fixed-variant": "#1b503a",
        "background": "#fff8f0",
        "surface-variant": "#e9e2d4",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fff8f0",
        "error-container": "#ffdad6",
        "surface-tint": "#356851",
        "tertiary-fixed-dim": "#f8bb6a",
        "surface-container-high": "#efe7d9",
        "secondary-fixed-dim": "#c9c6c1"
      },
      fontFamily: {
        "headline": ["Cabinet Grotesk", "sans-serif"],
        "body": ["Sora", "sans-serif"],
        "label": ["Sora", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    }
  },
  plugins: [],
}
